### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by mendel3** [VolVox99/Zoom-Joiner#1]
Hi,
I came across this and this will be super helpful to me, but I would remove your zoom links and the shortcut, as they leak private info (the shortcut leaks your windows user). I was trying to make it so that the zoom links could update dynamically from google calendar, but kinda gave up (it works but is ugly af)

**Comment by VolVox99** [comment]
yeah, i was planning on making it private at first but it would be a hassle to individually invite all of my friends to see it, so I just made it public and hoped no one unwanted would stumble upon it.  Thanks for letting me know about the shortcut though I didnt know that.

**Comment by VolVox99** [comment]
thanks for letting me know about the shortcut though I didnt know that.
